export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_AUTH_STATE_CHANGE = 'USER_AUTH_STATE_CHANGE'
export const CLEAR_DATA = 'CLEAR_DATA'
export const STORE_TOAST_REF = 'STORE_TOAST_REF'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'

//ADMIN
export const OPEN_TICKETS_COUNT_CHANGE = 'OPEN_TICKETS_COUNT_CHANGE'
export const CLOSED_TICKETS_COUNT_CHANGE = 'CLOSED_TICKETS_COUNT_CHANGE'
export const OPEN_TICKETS_STATE_CHANGE = 'OPEN_TICKETS_STATE_CHANGE'
export const CLOSED_TICKETS_STATE_CHANGE = 'CLOSED_TICKETS_STATE_CHANGE'

//USER TICKETS
export const OFFERS_STATE_CHANGE = 'OFFERS_STATE_CHANGE'
export const UNLOCKED_STATE_CHANGE = 'UNLOCKED_STATE_CHANGE'